### ISSUE TITLE
String#classify broke rails cache sweepers

### ISSUE THREAD

**Issue by valodzka** [cjohansen/juicer#11]
Here's trace:

```
app/vendor/bundler_gems/gems/juicer-0.2.6/lib/juicer/core.rb:19:in `to_class'
ruby/gems/1.8/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:380:in `inject'
app/vendor/bundler_gems/gems/juicer-0.2.6/lib/juicer/core.rb:18:in `each'
app/vendor/bundler_gems/gems/juicer-0.2.6/lib/juicer/core.rb:18:in `inject'
app/vendor/bundler_gems/gems/juicer-0.2.6/lib/juicer/core.rb:18:in `to_class'
app/vendor/bundler_gems/gems/juicer-0.2.6/lib/juicer/core.rb:28:in `classify'
ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/caching/sweeping.rb:43:in `cache_sweeper'
ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/caching/sweeping.rb:41:in `each'
ruby/gems/1.8/gems/actionpack-2.3.4/lib/action_controller/caching/sweeping.rb:41:in `cache_sweeper'
app/app/controllers/forums_controller.rb:6
```

Adding  unless String.method_defined?(:classify) solves issue

**Comment by cjohansen** [comment]
Thanks, this is solved now
