### ISSUE TITLE
Build fails on latest dev build

### ISSUE THREAD

**Issue by skyzyx** [cjohansen/juicer#16]
Running Mac OS X 10.6.2 with Ruby 1.8.7 and RubyGems 1.3.5. It seems to work fine on my 32-bit machine, but not my 64-bit machine. Not sure why.

When building the latest source from the Git master branch, I run the following commands:

```
mkdir -p ~/source
cd ~/source
sudo rm -Rf ~/source/juicer
sudo rm -Rf ~/.juicer
git clone git://github.com/cjohansen/juicer.git
cd ~/source/juicer
sudo rake build install
```
## 

I run into this error message:

```
$ juicer/opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer/cache_buster.rb:68: warning: already initialized constant DEFAULT_PARAMETER/opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:6: warning: already initialized constant VERSION
/opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:7: warning: already initialized constant LIBPATH
/opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:8: warning: already initialized constant PATH
/opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:9: warning: already initialized constant LOGGER
/opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer/install closure_compiler_installer.rb:11: uninitialized constant Juicer::Install::Base (NameError)
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:62:in `require_all_libs_relative_to'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:62:in `each'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:62:in `require_all_libs_relative_to'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:67
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer/install/base.rb:4
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:62:in `require_all_libs_relative_to'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:62:in `each'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:62:in `require_all_libs_relative_to'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/lib/juicer.rb:67
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
from /opt/local/lib/ruby/gems/1.8/gems/juicer-1.0.0/bin/juicer:5
from /opt/local/bin/juicer:19:in `load'
from /opt/local/bin/juicer:19
```
## 

Ideas?

**Comment by ktheory** [comment]
Just a guess...but do you already have juicer 1.0.0 installed in /opt/local/lib?

It's a bit non-standard to have /opt/local/lib in your load path, but it should still work. I suspect the build process is requiring the /opt/local/lib juicer instead of the one in ~/source/juicer.

If juicer is installed in /opt/local/lib, try uninstalling it, then building from source. Or muck with your LOAD_PATH to make sure ./lib is before  /opt/local/lib.

If that doesn't work, try running rake build install with the -t flag for more verbose output. That will report exactly which task is failing (the build task invokes several other tasks).

**Comment by ktheory** [comment]
Ah, I would get the same error when I ran `juicer install yui_compressor` using the latest master.

Some Juicer::Install submodules aren't requiring juicer/install/base. I have a patch on my topic branch, fix_install_tasks: http://github.com/ktheory/juicer/tree/fix_install_tasks

**Comment by cjohansen** [comment]
Thanks for this and sorry for the late reply! I'll pull now. I've been using the latest build to try it out, but ironycally I already had the tools installed and never tried the install command...
