### ISSUE TITLE
LoadError for Init_nokogiri when installing yui_compressor and jslit

### ISSUE THREAD

**Issue by jenshedqvist** [cjohansen/juicer#25]
I'm using cmd on Win 7 and I have installed juicer but when I try to install yui_compressor and jslint i get this error (the bit that need translation means it can't find the procedure):

```
    <internal:lib/rubygems/custom_require>:29:in `require': 127: Det gÕr inte att hitta den   angivna proceduren.   - Init_nokogiri (LoadError)
   C:/Ruby192/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.4-x86-mingw32/lib/nokogiri/1.9/nokogiri.so
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.4-x86-mingw32/lib/nokogiri/nokogiri.rb:1:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/nokogiri-1.4.4-x86-mingw32/lib/nokogiri.rb:13:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/juicer-1.0.8/lib/juicer/install/base.rb:1:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/juicer-1.0.8/lib/juicer.rb:61:in `block in require_all_libs'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/juicer-1.0.8/lib/juicer.rb:61:in `each'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/juicer-1.0.8/lib/juicer.rb:61:in `require_all_libs'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/juicer-1.0.8/lib/juicer.rb:66:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from C:/Ruby192/lib/ruby/gems/1.9.1/gems/juicer-1.0.8/bin/juicer:3:in `<top (required)>'
    from C:/Ruby192/bin/juicer:19:in `load'
    from C:/Ruby192/bin/juicer:19:in `<main>'
```

**Comment by cjohansen** [comment]
This is Nokogiri not working right. Unfortunately I have no idea why this happens. It may be a problem with the Nokogiri binary/Ruby 1.9.2/Win7 combination? Not seeing this locally (Linux).

**Comment by stereobooster** [comment]
no problems with nokogiri 1.4.4.1-x86-mingw32
