### ISSUE TITLE
Getting the rhino dependency can fail

### ISSUE THREAD

**Issue by olleolleolle** [cjohansen/juicer#30]
I had a problem getting juicer to install the rhino dependency.

```
[olle@mymachine /usr/local]$ juicer install yui_compressor
Installing Yui Compressor 2.4.6 in /home/olle/.juicer/lib/yui_compressor
Downloading http://yuilibrary.com/downloads/yuicompressor/yuicompressor-2.4.6.zip
Successfully installed YuiCompressor 2.4.6 in /home/olle/.juicer/lib/yui_compressor
[olle@dev30 /usr/local]$ juicer install jslint
Installing JsLint 1.0 in /home/olle/.juicer/lib/jslint
Installing dependencies
Installing Rhino 1_7R2-RC1 in /home/olle/.juicer/lib/rhino
Downloading http://ftp.mozilla.org/pub/mozilla.org/js/rhino1_7R2-RC1.zip
/usr/local/lib/ruby/1.8/open-uri.rb:277:in `open_http': 404 Not Found (OpenURI::HTTPError)
  from /usr/local/lib/ruby/1.8/open-uri.rb:616:in `buffer_open'
  from /usr/local/lib/ruby/1.8/open-uri.rb:164:in `open_loop'
  from /usr/local/lib/ruby/1.8/open-uri.rb:162:in `catch'
  from /usr/local/lib/ruby/1.8/open-uri.rb:162:in `open_loop'
  from /usr/local/lib/ruby/1.8/open-uri.rb:132:in `open_uri'
  from /usr/local/lib/ruby/1.8/open-uri.rb:518:in `open'
  from /usr/local/lib/ruby/1.8/open-uri.rb:30:in `open'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:134:in `download'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:133:in `open'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:133:in `download'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/rhino_installer.rb:26:in `install'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:79:in `install'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:170:in `call'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:170:in `dependencies'
  from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `collect'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:167:in `each'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:167:in `collect'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:167:in `dependencies'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/base.rb:79:in `install'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/install/jslint_installer.rb:29:in `install'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/command/install.rb:49:in `execute'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/command/install.rb:39:in `each'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/command/install.rb:39:in `execute'
  from /usr/local/lib/ruby/gems/1.8/gems/cmdparse-2.0.3/lib/cmdparse.rb:436:in `parse'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/cli.rb:27:in `parse'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/lib/juicer/cli.rb:37:in `run'
  from /usr/local/lib/ruby/gems/1.8/gems/juicer-1.0.9/bin/juicer:6
  from /usr/local/bin/juicer:19:in `load'
  from /usr/local/bin/juicer:19
```

**Comment by olleolleolle** [comment]
juicer (1.0.9) was the affected version.

**Comment by olleolleolle** [comment]
http://ftp.mozilla.org/pub/mozilla.org/js/rhino1_7R3.zip exists, since May 9, 2011, though.

**Comment by olleolleolle** [comment]
https://gist.github.com/c4463f0c41315170657f is a random change, at least indicating where that string was used. Why are you downloading >1 Rhino?

**Comment by cjohansen** [comment]
Eh, that test case isn't all it could be... Anyway I fixed the error by not hard-coding the Rhino version in install/rhino.rb. Now it detects the newest version and downloads that. 1.0.10 is pushed to rubygems, may be a few minutes before it's readily available.
