### ISSUE TITLE
yui_compressor is now on github—installation fails

### ISSUE THREAD

**Issue by frankrue** [cjohansen/juicer#60]
Appears that the yui_compressor moved to github (yay!) but now the attempt to install it fails.

**Comment by wei2912** [comment]
Same problem too. This is due to the blocking of redirection:

```
wei2912@wei2912-server:~/Downloads$ juicer install yui_compressor
/usr/lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://yuilibrary.com/download/yuicompressor/ ->    https://github.com/yui/yuicompressor/downloads (RuntimeError)
from /usr/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
from /usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
from /usr/lib/ruby/1.9.1/open-uri.rb:33:in `open'
from /var/lib/gems/1.9.1/gems/juicer-1.0.16/lib/juicer/install/yui_compressor_installer.rb:63:in `latest'
from /var/lib/gems/1.9.1/gems/juicer-1.0.16/lib/juicer/command/install.rb:57:in `version'
from /var/lib/gems/1.9.1/gems/juicer-1.0.16/lib/juicer/command/install.rb:42:in `block in execute'
from /var/lib/gems/1.9.1/gems/juicer-1.0.16/lib/juicer/command/install.rb:39:in `each'
from /var/lib/gems/1.9.1/gems/juicer-1.0.16/lib/juicer/command/install.rb:39:in `execute'
from /var/lib/gems/1.9.1/gems/cmdparse-2.0.5/lib/cmdparse.rb:464:in `parse'
from /var/lib/gems/1.9.1/gems/juicer-1.0.16/lib/juicer/cli.rb:27:in `parse'
from /var/lib/gems/1.9.1/gems/juicer-1.0.16/lib/juicer/cli.rb:37:in `run'
from /var/lib/gems/1.9.1/gems/juicer-1.0.16/bin/juicer:6:in `<top (required)>'
from /usr/local/bin/juicer:19:in `load'
from /usr/local/bin/juicer:19:in `<main>'
```

**Comment by cjohansen** [comment]
Fixed. Upgrade Juicer.
