### ISSUE TITLE
Can't install YUI Compressor on windows 2008 when specifying version

### ISSUE THREAD

**Issue by xnzhu** [cjohansen/juicer#66]
Hi,

I've tried to install YUI Compressor on Windows Server 2008 R2, Ruby version: ruby 1.8.7 (2010-12-23 patchlevel 330) [i386-mingw32]. Already installed juicer 1.0.18.

When tried to run: juicer install -v 2.4.7 yui_compressor, got the error:

C:/Ruby187/lib/ruby/gems/1.8/gems/juicer-1.0.18/lib/juicer/install/yui_compressor_installer.rb:33:in `+': can't convert nil into String (TypeError)
        from C:/Ruby187/lib/ruby/gems/1.8/gems/juicer-1.0.18/lib/juicer/install/yui_compressor_installer.rb:33:in`install'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/juicer-1.0.18/lib/juicer/command/install.rb:49:in `execute'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/juicer-1.0.18/lib/juicer/command/install.rb:39:in`each'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/juicer-1.0.18/lib/juicer/command/install.rb:39:in `execute'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/cmdparse-2.0.3/lib/cmdparse.rb:436:in`parse'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/juicer-1.0.18/lib/juicer/cli.rb:27:in `parse'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/juicer-1.0.18/lib/juicer/cli.rb:37:in`run'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/juicer-1.0.18/bin/juicer:6
        from C:/Ruby187/bin/juicer:19:in `load'
        from C:/Ruby187/bin/juicer:19

---

If no version specficed, got certificate verification error, which is already issued in #64

**Comment by jmkacz** [comment]
I just received that error when my provisioning scripts ran on launching an EC2 instance. My issue is that there was no HOME variable set, at the time.

In general, if the self.home method, in lib/juicer.rb returns nil, you will get the error above. It checks for JUICER_HOME, HOME, APPDATA, HOMEDRIVE and HOMEPATH, USERPROFILE, or Personal environment variables.

Near as I can tell, it uses self.home as the staging area to download and extract the relevant zip file.

Since "Personal" is not used anywhere else in the library, I've started using to specify a directory under /tmp, and my install is now functioning.
