### ISSUE TITLE
juicer install yui_compressor fails / open_loop: redirection forbidden

### ISSUE THREAD

**Issue by wazum** [cjohansen/juicer#76]
```
    # juicer install yui_compressor
    Installing Yui Compressor 2.4.7 in /home/…/.juicer/lib/yui_compressor
    Downloading http://cloud.github.com/downloads/yui/yuicompressor/yuicompressor-2.4.7.zip
    /usr/lib/ruby/1.9.1/open-uri.rb:216:in `open_loop': redirection forbidden: http://cloud.github.com/downloads/yui/yuicompressor/yuicompressor-2.4.7.zip -> https://cloud.github.com/downloads/yui/yuicompressor/yuicompressor-2.4.7.zip (RuntimeError)
            from /usr/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
            from /usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
            from /usr/lib/ruby/1.9.1/open-uri.rb:33:in `open'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/install/base.rb:134:in `block in download'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/install/base.rb:133:in `open'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/install/base.rb:133:in `download'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/install/yui_compressor_installer.rb:34:in `install'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/command/install.rb:49:in `block in execute'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/command/install.rb:39:in `each'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/command/install.rb:39:in `execute'
            from /var/lib/gems/1.9.1/gems/cmdparse-2.0.6/lib/cmdparse.rb:464:in `parse'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/cli.rb:27:in `parse'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/lib/juicer/cli.rb:37:in `run'
            from /var/lib/gems/1.9.1/gems/juicer-1.1.1/bin/juicer:6:in `<top (required)>'
            from /usr/local/bin/juicer:23:in `load'
            from /usr/local/bin/juicer:23:in `<main>'
```

**Comment by cjohansen** [comment]
So... Looks like someone changed something on the YUI side again. PR welcome.

**Comment by ku1ik** [comment]
Same thing on ruby 2.0. Any workarounds?
