### ISSUE TITLE
With fresh install, `juicer` command causes an error

### ISSUE THREAD

**Issue by zachschultz** [cjohansen/juicer#79]
I have just installed `juicer` and when I try to run `juicer install yui_compressor` or just `juicer` I get this error:

```
/Users/<my account>/.rvm/gems/ruby-2.2.1/gems/cmdparse-3.0.1/lib/cmdparse.rb:796:in `initialize': wrong number of arguments (2 for 0) (ArgumentError)
from /Users/zach/.rvm/gems/ruby-2.2.1/gems/juicer-1.2.0/lib/juicer/cli.rb:16:in `new'
from /Users/zach/.rvm/gems/ruby-2.2.1/gems/juicer-1.2.0/lib/juicer/cli.rb:16:in `parse'
from /Users/zach/.rvm/gems/ruby-2.2.1/gems/juicer-1.2.0/lib/juicer/cli.rb:37:in `run'
from /Users/zach/.rvm/gems/ruby-2.2.1/gems/juicer-1.2.0/bin/juicer:6:in `<top (required)>'
from /Users/zach/.rvm/gems/ruby-2.2.1/bin/juicer:23:in `load'
from /Users/zach/.rvm/gems/ruby-2.2.1/bin/juicer:23:in `<main>'
from /Users/zach/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
from /Users/zach/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by cjohansen** [comment]
I don't maintain Juicer anymore, I suggest you look for an alternative.

**Comment by ghost** [comment]
I'm sorry to hear that. I'm very grateful for Juicer, as it served me well for many years.
Would you mind recommending an alternative, or a good starting point to look for alternatives?

**Comment by ghost** [comment]
BTW, answering the original question, the problem is that Juicer doesn't seem to play well with cmdparse 3.0.1. To fix it, this worked for me:

`$ gem uninstall cmdparse`
`$ gem install cmdparse --version 2.0.6`

**Comment by rareyman** [comment]
@lucianop Thanks for the fix/workaround. :) Also, if anyone has found any alternatives to Juicer, please post here. I primarily use it to merge and minify css files only.

**Comment by monecchi** [comment]
Yeah! indeed it solved the issue! Thanks a lot for the input.

**Comment by lkwg82** [comment]
@cjohansen maybe you write that in the readme? Would be nice. Thx.

**Comment by sys0dm1n** [comment]
Thank you @lucianop for the fix. Worked for me.

**Comment by quicken** [comment]
@lucianop Thank you so much for posting your workaround.
