### ISSUE TITLE
Juicer on OSX El Capitan ~ wrong number of arguments (2 for 0) (ArgumentError) 

### ISSUE THREAD

**Issue by novalagung** [cjohansen/juicer#81]
I've installed juicer on my osx el capitan (I use ruby which is installed from homebrew), and I got this error. Previously when I used maverick, there was no problem (I use the same version of juicer, **1.2.0**).

``` bash
novalagung:~ $ juicer
/usr/local/lib/ruby/gems/2.2.0/gems/cmdparse-3.0.1/lib/cmdparse.rb:796:in `initialize': wrong number of arguments (2 for 0) (ArgumentError)
    from /usr/local/lib/ruby/gems/2.2.0/gems/juicer-1.2.0/lib/juicer/cli.rb:16:in `new'
    from /usr/local/lib/ruby/gems/2.2.0/gems/juicer-1.2.0/lib/juicer/cli.rb:16:in `parse'
    from /usr/local/lib/ruby/gems/2.2.0/gems/juicer-1.2.0/lib/juicer/cli.rb:37:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/juicer-1.2.0/bin/juicer:6:in `<top (required)>'
    from /usr/local/bin/juicer:23:in `load'
    from /usr/local/bin/juicer:23:in `<main>'
novalagung:~ $ 
```

What should I do?

**Comment by variousred** [comment]
i'm getting this same thing

**Comment by sidoh** [comment]
Same here. My stacktrace:

```
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cmdparse-3.0.1/lib/cmdparse.rb:796:in `initialize': wrong number of arguments (given 2, expected 0) (ArgumentError)
    from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/juicer-1.2.0/lib/juicer/cli.rb:16:in `new'
    from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/juicer-1.2.0/lib/juicer/cli.rb:16:in `parse'
    from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/juicer-1.2.0/lib/juicer/cli.rb:37:in `run'
    from /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/juicer-1.2.0/bin/juicer:6:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.3.0/bin/juicer:23:in `load'
    from /usr/local/var/rbenv/versions/2.3.0/bin/juicer:23:in `<main>'
```

**Comment by ghost** [comment]
Any resolution to this?
